# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  servlet.context-path: /mk

# mysql
spring:
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    redis:
        open: false  #
        database: 0
        host: localhost
        port: 16379
        password:       #
    mvc.favicon.enabled: false

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  #    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      first:
        url: jdbc:mysql://192.168.1.115:3306/sys?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: Sipaote2019@
      second:  #数据源2
        url: jdbc:mysql://gepan8.cn:3306/sys?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: gepan
        password: GePan_88
      initial-size: 10
      min-idle: 5
      max-active: 100
      max-wait: 60000
      max-pool-size: 50
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: false
      test-on-return: false
      test-on-borrow: false
      filters: stat,wall,log4j2
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  mapper-locations: classpath:xml/*Mapper.xml
  typeAliasesPackage: com.monkey.entity
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #序列接口实现类配置
    #key-generator: cn.crm.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    db-config:
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    call-setters-on-nulls: true



